### ISSUE TITLE
Memory Leak on frequent media change

### ISSUE THREAD

**Issue by kschwarz1980** [Sascha-L/WPF-MediaKit#5] opened 2015-09-17 13:16 UTC
Hello Sascha, 

I just got some time to test your implementation, which is pretty impressive! 
One thing I currently struggle with a large memory leak: 
I developed a WPF application that shows images and videos that are located in a folder one after another with a nice fade effect by using two MediaUriElement controls and animating their opacity. With every image change the application uses about 30-50 MB more space RAM, and at about 600 MB it crashes with a "no more memory" error message. 

I can provide an example project if needed. 

Kind regards, 
Klemens

**Comment by rchristilaw** [comment] 2015-11-05 14:53
Hello Klemens,

Are you using the EVR presenter? I created a WPF Application also that has a macro to switch video streams in a bank of 4 monitors. Each time I switch video streams I tear down and open a new EVR Presenter. I have narrowed it down to this area. It seems there is a handle leak in the C++ Evr Component (~16 handles remain open after I start and stop a video stream). Do you have a similar experience? Any input Sascha?

Thanks,

Ryan

**Comment by kschwarz1980** [comment] 2015-11-09 14:36
Hi Ryan, 

no, I am using the WPFMediaKit.DirectShow.Controls.MediaUriElement control and the functions/properties as follows: 
grid.Children.Clear();
MediaUriElement media = new MediaUriElement();
media.Loop = true; 
media.LoadedBehavior = WPFMediaKit.DirectShow.MediaPlayers.MediaState.Manual; 
media.UnloadedBehavior = WPFMediaKit.DirectShow.MediaPlayers.MediaState.Stop; 
media.Volume = _viewModel.Background.IsVideoMuted ? 0 : 1;
if (System.IO.File.Exists(videoFilename))
{
     media.Source = new Uri(videoFilename, UriKind.RelativeOrAbsolute);
     this.btnPlayMedia.ToolTip = "Video: " + videoFilename;
}
media.Stretch = Stretch.Uniform;
if (_viewModel.Background.FitToPage)
    media.Stretch = Stretch.Fill;
grid.Children.Add(media);
if (isPlaying)
    media.Play();
else
    media.Stop();

**Comment by kschwarz1980** [comment] 2015-11-09 14:43
Hi Ryan again, 

ah yes, as VideoRenderer is the EVR set. 

Best regards, 
Klemens

**Comment by rchristilaw** [comment] 2015-11-17 13:38
Klemens,

I will let you know if I figure anything out. I spent some time on the leak but needed to move on to something else. 

Ryan

**Comment by kschwarz1980** [comment] 2016-01-11 06:39
Hi Ryan, 

do you have any news regarding the memory leak issue? 

Kind regards, 
Klemens

**Comment by rchristilaw** [comment] 2016-01-11 14:15
Klemens,

The issue is still outstanding for me. I hope to look into it soon and can hopefully find a solution.

Ryan

**Comment by gdecosterd** [comment] 2016-01-20 09:32
Hi Ryan and Klemens,

I've seen the new version of EVRPresenter and all great job and great new functionalities available. So I changed from the old EVRPresenter64.dll (release 1.5) to the last one v2.0 and ran into the same problem with handles :(

I've got a software displaying various content (videos, DVD, capture devices, ...), all using excusively EVR. I let the software run with the new EVRPresenter for about 10 hours on three computers. One crashed after an hour, the second one after 4 hours and the last one is still running but uses now 80'000 handles.

I'm sure the leak is in EVRPresenter as it was running OK with the old version and nothing else changed. It looks like you are working on a solution? Do you think you'll find something very soon or should I rollback my changes?

Thank you in advance for your help & replies.

Gaël

**Comment by rchristilaw** [comment] 2016-01-20 14:04
Hi Gaël,

I have spent some time trying to find the leak but with no success.

Just wondering where I could get a copy of the code from release 1.5 and what is different in the new version 2 compared to the old version.

I would like to try the old presenter you are talking about in order to see if it solves my problem and still has the functionality that I am looking for. Then maybe comparing the two I could try to find where things went wrong.

Thanks,

Ryan

**Comment by gdecosterd** [comment] 2016-01-21 08:02
Hi Ryan,

Unfortunately I can't help much on EVR code as this is c++ and I don't understund it as well as C# and other object-oriented languages.

However I think from what I read on the websites (old mediakit and new one) that the current (new version 2.0) includes DXVA decoding and some other new stuff about graphs. I can imagine that the leak is located somewhere there or in new dependancies?

Is there any way we can deactivate some parts of the codes (graph changes or DXVA) so we can retest without these functionalities and locate the problem?

You can find the old code I used on the old website, both EVR and mediakit v1.5 source & binaries (https://wpfmediakit.codeplex.com/SourceControl/latest). I always worked with the already compiled EVR dlls from the downloadable realease while using mediakit source code at the same time.

Other things I've seen with the new version (don't know if it could be related):
- The register callback method has been moved (or duplicated?) from IEVRPresenterRegisterCallback to IEVRPresenterSettings
- The new EVR seems to not work correctly if not calling GetBufferCount. The old EVR did not need that.
- With new EVR, it seems like when I load the graph for the first time, the first played video starts then makes a short pause and then continues. Did not see that behaviour before.
- Loading EVR dlls (both new and old) using the "old way" in EvrPresenter.cs (using DLLImport attribute) seems to work for both (old and new) and therefore excludes that the leak is located in c# part of the code
- When loading many videos in parralele using old EVR (don't know if it is still the case with the new one), the section where we create the presenter, set the callback, setVideoWindow handle, .. must be thread safe and in a specific order (otherwise it crashes, but not always..)
- I've got one more thing with the D3D object lock when setting backbuffer in multithreaded app but didn't find why nor how to solve it for now.

Don't know if all these details might help? Maybe the one who made all the additional changes in EVR might help a bit more?

Let me know if I can help in any way.

Best Regards,
Gaël

**Comment by gdecosterd** [comment] 2016-01-27 08:00
Any news?

Is there any way to contact Sascha as he seems to be the one who did all the great changes inside EVR Presenter. He might surely be able to help?

**Comment by rchristilaw** [comment] 2016-02-01 17:03
Hi Gaël,

I tried the old presenter and it seemed to behave the same way as the new one for me unfortunately. 

The area I suspect to contain the handle leak is the scheduler thread in the Presenter. When I execute actions on my directshow graph which causes the OnClockStart, OnClockStop, etc. methods to be called and the scheduler thread is stopped, destroyed and restarted, more handles are added to the process. However, I couldn't yet find anywhere that would be leaking handles in that area.

As per your points you mentioned:

_The register callback method has been moved (or duplicated?) from IEVRPresenterRegisterCallback to IEVRPresenterSettings_
This just added a method to the interface (I did notice it was not removed from the old one though) however I don't think this is a factor.

_The new EVR seems to not work correctly if not calling GetBufferCount. The old EVR did not need that._
I do not call GetBufferCount and my video plays properly.

_With new EVR, it seems like when I load the graph for the first time, the first played video starts then makes a short pause and then continues. Did not see that behaviour before._
I do not see this.

_Loading EVR dlls (both new and old) using the "old way" in EvrPresenter.cs (using DLLImport attribute) seems to work for both (old and new) and therefore excludes that the leak is located in c# part of the code_
I have tried also not using COM to load this DLL directly. In my application, I made a C++ component which makes the calls to Directshow (instead of using DirectShow.net) and I have tried using the EvrPresenter directly by creating/destroying the object manually using the lib file but the leak is still there so it seems it is deeper than the general loading of the presenter.

_When loading many videos in parralele using old EVR (don't know if it is still the case with the new one), the section where we create the presenter, set the callback, setVideoWindow handle, .. must be thread safe and in a specific order (otherwise it crashes, but not always..)_
I do notice occasional crashes when loading multiple video streams, especially after switching videos for a while.

Also, there has been no activity from Sascha since I first visited. I also looked at the projects that have forked from this but noticed no recent activity or changes related to our issue there either.

I will let you know if I have any success. My efforts in this area are off and on depending on how busy I am so hopefully I have some time to put into it soon.

Ryan

**Comment by xmedeko** [comment] 2016-11-15 06:35
Is this same problem as #21 ?

**Comment by xmedeko** [comment] 2017-01-18 10:01
Hello, can you try the latest source, with the fix #27?

**Comment by xmedeko** [comment] 2017-03-13 11:57
Closing as probably fixed.

**Closed by xmedeko** 2017-03-13 11:57 UTC

**Comment by kschwarz1980** [comment] 2017-04-25 18:57
I could finally test the newest version integrated into a test project, and voila: no more memory leaks! Thats great, thank you so much!!!
