### ISSUE TITLE
How an I setup New Frame listener for VideoCaptureElement

### ISSUE THREAD

**Issue by bbetter** [Sascha-L/WPF-MediaKit#68] opened 2017-11-26 19:36 UTC
I need to detect whether qr code is present in each frame of web cam output,
How can i get this callback?

**Comment by xmedeko** [comment] 2017-11-27 19:48
Check `NewVideoSample` event.

**Comment by bbetter** [comment] 2017-12-03 21:00
Sorry for not responding for a long time, the problem is that i'm out of ideas , it never enters this callback
`
   public QrScannerControl()
        {
            InitializeComponent();
            VideoCapElement.EnableSampleGrabbing = true;
            VideoCapElement.NewVideoSample += (sender, args) =>
            {
                var binBitmap = new BinaryBitmap(new HybridBinarizer(new BitmapLuminanceSource(args.VideoFrame)));

                BitMatrix bm = binBitmap.BlackMatrix;
                Detector detector = new Detector(bm);
                DetectorResult detectorResult = detector.detect();

                string retStr = "Found at points ";
                foreach (ResultPoint point in detectorResult.Points)
                {
                    retStr += point.ToString() + ", ";
                }

                Console.WriteLine(retStr);
                var result = _qrCodeReader.decode(binBitmap);
                if (result == null) return;
                OnQrDeoded?.Invoke(result.Text);
            };
//how should i make it start entering this callback? the play method way is not working
            VideoCapElement.Play();
        }

`

**Comment by xmedeko** [comment] 2017-12-04 08:31
Duplicate of #6 ?

**Closed** 2017-12-08 07:49 UTC
Labels: question
