### ISSUE TITLE
SpeedRatio is ignored

### ISSUE THREAD

**Issue by tpgalan** [Sascha-L/WPF-MediaKit#34] opened 2017-01-31 08:42 UTC
Hi, 

When I play a video and change the `SpeedRatio` value it has no effect.

My code example:

```
mediaUriElement.Source = new Uri(@"test.mp4");
mediaUriElement.SpeedRatio = 4.0;
```

Is this correct?

**Comment by xmedeko** [comment] 2017-01-31 19:05
Set the speed ration after the media has been opened (the ``MediaOpened`` event).

**Comment by skaterlui** [comment] 2017-11-08 20:54
Hello tpgalan,

I use the speed ratio thing a lot. It depends on the codec which is used to decode the media if it supports speed ratio setting or not. It doesn't matter if speed ratio is set after or before media is opened. With h.264 speed ratio 4.0 is the maximum I get with K-Lite-Codec-Pack and LAV. If I set it to 8.0, the setting is ignored and speed ratio is still 4.0. I have no special tweaks in K-Lite. I attached my settings.
[CodecSettingsBackup20171108.zip](https://github.com/Sascha-L/WPF-MediaKit/files/1455372/CodecSettingsBackup20171108.zip)

Check this clip: https://www.youtube.com/watch?v=QVx-_HpHe7c

**Comment by skaterlui** [comment] 2017-11-09 20:52
@tpgalan 
You can also check this link from the old mediakit
https://wpfmediakit.codeplex.com/discussions/85603

**Comment by xmedeko** [comment] 2017-11-10 07:05
I am closing the issue. @tpgalan reopen it, if your problem is not caused by the codec.

You can also set a custom sync clock:
```c#
IMediaFilter filt = Graph as IMediaFilter;
clock = new MyCustomClock(); // DirectShowLib.IReferenceClock
filt.SetSyncSource(clock);
```

**Closed** 2017-11-10 07:06 UTC
Labels: question
