### ISSUE TITLE
Silently blank in software mode

### ISSUE THREAD

**Issue by yegorpetrov** [Sascha-L/WPF-MediaKit#3] opened 2015-08-04 11:29 UTC
D3DImage doesn't show up without hardware acceleration. The limitation is briefly described here: http://blogs.msdn.com/b/wpf3d/archive/2009/01/13/d3dimage-and-software-rendering.aspx

The kit should either report its inability to render video or use some sort of fallback. The new overload of the D3DImage.SetBackBuffer method in .NET 4.5 looks like a possible solution.

**Comment by Sascha-L** [comment] 2015-09-15 08:28
I don't have the experience/knowledge to fix this in the D3DImage implementation of WPF MediaKit. We need help! :-)

**Comment by ecoChahn** [comment] 2015-10-23 20:28
ran into this issue as well.  the new overload for D3DImage.SetBackBuffer did do the trick for me.

When i tried it out, however, it seems I was still getting **D3DImage.IsFrontBufferAvailable = false**,
so even the backBuffer does not get written to inside **InternalInvalidateVideoImage()**.

The result was seeing the first frame only, but an image did finally show up for me!

Removing the first condition from this check made it work:
**if (*D3DImage.IsFrontBufferAvailable* && IsRenderingEnabled && m_pBackBuffer != IntPtr.Zero)**
but probably don't want to do this ALL the time.  some more logic around this error could easily help to write a better fallback.

**Comment by BobDeCuir** [comment] 2016-11-29 17:28
I almost abandoned WPFMediaKit until I came across this solution. The .net 4.5 overload to fallback to software rendering was essential to getting the new version to work with any of my configurations. I also had to remove the test for D3DImage.IsFrontBufferAvailable. Once these two changes were made videos resumed playing as expected. Still don't know why hardware acceleration is disabled, but I'll leave that for another day.

Thanks!

**Comment by ecoChahn** [comment] 2016-11-29 18:48
For me, the problem was being caused by a bad configuration of some VNC software.  Specifically "My Video Hook Driver (2)" seems to be the culprit.  Re-installing, or just _UN-installing_ that, if you don't know why you have it, should resolve the issue (if that _is_ causing your problem).  

A quick google shows that many others have the same problem with this component.  That's all I can add to the knowledge-base at the moment... I hope it helps!

**Comment by xmedeko** [comment] 2017-09-03 20:51
Can you guys, make a PR to address this issue? Maybe with some switch "enable SW rendering", or just autoconfiguration by the `RenderCapability.Tier`.

**Comment by xmedeko** [comment] 2017-11-09 07:39
Closed by #62.

**Closed by xmedeko** 2017-11-09 07:39 UTC
