### ISSUE TITLE
MediaUriElement canot play mov with alpha channel

### ISSUE THREAD

**Issue by LazyCuteLion** [Sascha-L/WPF-MediaKit#45] opened 2017-08-16 09:42 UTC

**Comment by xmedeko** [comment] 2017-08-20 13:52
Do you have such mov? Have you tried it with WPF-MediaKit?

**Comment by LazyCuteLion** [comment] 2017-08-25 03:41
yes，and the mov play in MediaUriEment background is black

**Comment by xmedeko** [comment] 2017-08-25 18:41
Try:
- EVRPresenter (you must compile it from the included C++ code).
- Or try in the code to change all occurrences of `D3DFMT_X8R8G8B8` to the `D3DFMT_A8R8G8B8` in the `Vmr9Allocator`.

**Comment by birdcpe25** [comment] 2017-08-27 19:28
I'm facing the same problem, Cant view .mov video encoded using DVX3.

Tried both, 
> changed from "D3DFMT_X8R8G8B8" to "D3DFMT_A8R8G8B8" 
> or Set VideoRenderer="EnhancedVideoRenderer"

The pixel is filled with RGB color (no alpha included) [See Image](https://s2.postimg.org/3mlgc2g6h/aaaa1123123.png).

**Comment by xmedeko** [comment] 2017-08-28 07:11
We should figure out if the problem is in the codecs or WPF MediaKit.

- Do you have some player, where do you see the mov transparent? Is it DirectShow based player?
- Try MPC-HC player from [K-lite codecs ](https://github.com/Sascha-L/WPF-MediaKit/wiki/Codecs). If it's not transparent, try GraphStudioNext to see which codecs are used.

**Comment by birdcpe25** [comment] 2017-08-28 11:14
Hmmm, maybe it's because the codecs based on DirectShow.
I exported the .mov file from Adobe Effect using quicktime.

But when I tried using HAP alpha from [link](http://renderheads.com/product/hap-for-directshow/) exported as .avi file
Same problem still happened. 
Not sure why It's doesn't recognize as rgba video.

> General
Complete name               : *******\sample-1080p30-HapA.avi
Format                      : AVI
Format/Info                 : Audio Video Interleave
File size                   : 105 MiB
Duration                    : 10 s 0 ms
Overall bit rate            : 88.3 Mb/s
Recorded date               : 2014-03-26T09:47:17.00632
Writing application         : Adobe After Effects CC (Windows)
>Video
ID                          : 0
Format                      : Hap5
Codec ID                    : Hap5
Duration                    : 10 s 0 ms
Bit rate                    : 88.3 Mb/s
Width                       : 1 920 pixels
Height                      : 1 080 pixels
Display aspect ratio        : 16:9
Frame rate                  : 30.000 FPS
Bits/(Pixel*Frame)          : 1.419
Time code of first frame    : 00:00:00:00 / 00:00:00:00
Time code source            : Adobe tc_A / Adobe tc_O
Stream size                 : 105 MiB (100%)

Or maybe could you suggest file type that work with alpha? so I could give it a try.
(If I can't figure it out then I have to write mask and then overlay into graph maybe)
Thanks :)

**Comment by xmedeko** [comment] 2017-08-28 15:27
Have you tried it with HAP codecs installed - and try to force the HAP codecs for the MediaUriElement in the MPC-HC - set it by `VideoDecoder`?

As a workaround, you may export mov to animated PNG (APNG) and try normal WPF `Image` for that.

If you decide to go with the color keying - I may change the MediaUriElement to have a property Effect for writing custom effect. (Or you may try the `Effect` with the normal WPF `MediaPlayer`).

**Comment by birdcpe25** [comment] 2017-08-28 18:41
I couldn't figure out how to force using specify decoder, There's no VideoDecoder attributes for MediaUriElement only found VideoRenderer.

Anyway,
It'd be awesome to have alpha mask features so there will be video source and alpha mask source then composite, do overlay, or something later.

**Comment by xmedeko** [comment] 2017-08-29 05:25
Try in the code: `player.MediaUriPlayer.VideoDecoder = "..."`

About the `Effect`: you have to create own effect, probably `BitmapEffect` or `ShaderEffect` (see `DeeperColor` in the WPF MediaKit source). Anyway, why do you cannot use WPF `MediaPlayer`? IMO it should be possible to apply the effect for the `MediaPlayer`, too.

**Comment by birdcpe25** [comment] 2017-09-05 07:02
I've do some research and it's said that LAVFilter could decode media with alpha but the alpha is ignored.
Not sure if there's any alternative way.

**Comment by xmedeko** [comment] 2017-09-05 07:13
On which part is the alpha ignored - in the filter or later by WPF-MediaKit somewhere?

If you have just certain transparency levels, like lets say 100%, 75%, 50%, then you may do color keying with three colors. If you have variable transparency, then it;s not easily possible.

**Comment by birdcpe25** [comment] 2017-09-05 07:17
In the LAVFilter [LINK](https://github.com/Nevcairiel/LAVFilters/issues/90)

Some part is fading out while some part fading in. Quite hard using color keying.

**Comment by xmedeko** [comment] 2017-09-05 07:21
It's pitty LAVFilter cannot do alpha. Then I see just two options: try another filter (HAP, ffdshow - but it's quite obsolete) or do the animated PNG.

**Comment by birdcpe25** [comment] 2017-09-06 18:22
Another workaround options is to write own shader. with one movie contains both rgb and alpha.
> [Link Here](https://forum.unity3d.com/threads/chroma-key-shader.48938/ on the 11th comment
)

And write own pixelshader effect.
> [See more](http://scripter.co.kr/249)

With these method I think it enough while using provided MediaElement one.

**Comment by xmedeko** [comment] 2017-09-06 18:42
Interesting, let me know, if setting `MediaUriElement.Effect` is enough for you or if you need to access internal `VideoImage.Effect`.

**Comment by birdcpe25** [comment] 2017-09-07 10:01
@xmedeko,
I cant manage to run testapplication using DeeperColor effect from your repo.
It said "Cannot locate resource 'effects/deepercolor.ps'".

**Comment by birdcpe25** [comment] 2017-09-07 10:41
Okay just MediaElement.Effect works fine.
Just to share the work around. 
Here's my fx file.
```
sampler2D input : register(s0);
float4 main(float2 uv : TEXCOORD) : COLOR
{
	float4 color;
	float2 pColor;
	pColor.x = uv.x / 2;
	pColor.y = uv.y;
	color = tex2D(input , pColor.xy);
	float4 mapColor;
	float2 pMapColor;
	pMapColor.x = 0.5 + (uv.x / 2);
	pMapColor.y = uv.y;
	mapColor = tex2D(input, pMapColor.xy);
	color.a = mapColor.r;
	return color;
}
```
This one I'm using double size video from above which left is for rgb while right is for alpha.

**Comment by xmedeko** [comment] 2017-09-07 11:03
Thanks for sharing the code. Closing the issue.

**Closed by xmedeko** 2017-09-07 11:03 UTC
Labels: enhancement
